import SwiftUI
import SwiftData
import UserNotifications
import GoogleSignIn
import RevenueCat
import FirebaseCore
import FirebaseMessaging
import FirebaseAuth

// MARK: - AppDelegate (needed for FCM remote push token handling)

class AppDelegate: NSObject, UIApplicationDelegate,
                   UNUserNotificationCenterDelegate,
                   MessagingDelegate {

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        UNUserNotificationCenter.current().delegate = self
        Messaging.messaging().delegate = self

        // Ensure a Firebase Auth session exists. The Firestore security
        // rules require `request.auth != null` — without an auth session
        // EVERY read/write (device_tokens, user_notifications, even
        // support_tickets) fails with "Missing or insufficient
        // permissions".
        //
        // DiPo's own login (Apple/Google via UserSession) signs into
        // Firebase Auth only on a FRESH sign-in; a returning user restored
        // from Keychain never re-establishes it. Anonymous auth is the
        // guaranteed floor — it costs nothing and satisfies the rule.
        // The real Apple/Google Firebase sign-in still runs on fresh login
        // and simply replaces this anonymous session.
        //
        // Requires the "Anonymous" provider to be enabled in
        // Firebase Console → Authentication → Sign-in method.
        if Auth.auth().currentUser == nil {
            Auth.auth().signInAnonymously { _, error in
                if let error {
                    print("[DiPo] Anonymous Firebase auth failed: \(error.localizedDescription)")
                } else {
                    print("[DiPo] Anonymous Firebase auth established ✓")
                    // Auth is ready now — re-run device-token registration
                    // in case the FCM token arrived before auth was up.
                    Task { await FirebaseSupportService.shared.registerCurrentDeviceToken() }
                }
            }
        }
        return true
    }

    // APNs → Firebase: pass the raw token so FCM can map it
    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }

    func application(_ application: UIApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("[DiPo] Remote notification registration failed: \(error)")
    }

    // FCM token refreshed — update in Firestore so admin panel always has the latest
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        guard let token = fcmToken else { return }
        print("[DiPo] FCM token: \(token)")
        UserDefaults.standard.set(token, forKey: "dipo_fcm_token")
        // Update token on any open tickets so admin can reach this device
        Task { await FirebaseSupportService.shared.updateFCMToken(token) }
    }

    // Show notification banner even when app is in foreground.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler handler: @escaping (UNNotificationPresentationOptions) -> Void) {
        // Mirror admin / remote pushes into the in-app notification center
        // so they're not lost the moment the OS banner is dismissed. We
        // only mirror REMOTE pushes (UNPushNotificationTrigger) — local
        // pushes are already either generated BY the in-app center
        // (post()'s "inapp_mirror_" pushes) or have their own in-app twin
        // (card expiry, overspend), so re-mirroring them would duplicate.
        if notification.request.trigger is UNPushNotificationTrigger {
            let content = notification.request.content
            Task { @MainActor in Self.mirrorRemotePushToInApp(content) }
        }
        handler([.banner, .sound, .badge])
    }

    // Fired when the user taps a delivered notification. Mirror remote
    // pushes here too — covers the case where an admin push arrived while
    // the app was backgrounded (willPresent never ran) and the user taps
    // it to open the app.
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler handler: @escaping () -> Void) {
        if response.notification.request.trigger is UNPushNotificationTrigger {
            let content = response.notification.request.content
            Task { @MainActor in Self.mirrorRemotePushToInApp(content) }
        }
        handler()
    }

    // Silent / data remote push (content-available) — gives the app a brief
    // window to mirror an admin push into the in-app center even when it
    // arrived in the background.
    func application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler handler: @escaping (UIBackgroundFetchResult) -> Void) {
        // Admin pushes carry `source: "admin"` — skip the bell-mirror here,
        // the Firestore `user_notifications` listener is the authoritative
        // bell source for those (it persists + replays on app open).
        if !Self.isAdminPush(userInfo),
           let aps = userInfo["aps"] as? [AnyHashable: Any],
           let alert = aps["alert"] as? [AnyHashable: Any] {
            let title = alert["title"] as? String ?? ""
            let body  = alert["body"]  as? String ?? ""
            if !title.isEmpty || !body.isEmpty {
                Task { @MainActor in
                    NotificationManager.shared.post(AppNotificationItem(
                        icon: "megaphone.fill", iconColorHex: "#A78BFA",
                        title: title, body: body,
                        time: loc("notif.time.now"), isUrgent: true
                    ), pushToDevice: false)
                }
            }
        }
        handler(.newData)
    }

    /// True when the push originated from the admin panel. Admin FCM
    /// payloads include `data: { source: "admin" }`. We let those skip the
    /// generic bell-mirror because the Firestore broadcast listener already
    /// guarantees they reach the in-app bell — mirroring here too would
    /// double-record them.
    private static func isAdminPush(_ userInfo: [AnyHashable: Any]) -> Bool {
        (userInfo["source"] as? String) == "admin"
    }

    /// Extracts title/body from a notification's content and adds it to the
    /// in-app notification center. `pushToDevice:false` — iOS already showed
    /// (or is about to show) the banner for this remote push.
    @MainActor
    private static func mirrorRemotePushToInApp(_ content: UNNotificationContent) {
        // Admin pushes are handled by the Firestore listener — don't mirror.
        if isAdminPush(content.userInfo) { return }
        let title = content.title.isEmpty ? content.subtitle : content.title
        let body  = content.body
        guard !title.isEmpty || !body.isEmpty else { return }
        NotificationManager.shared.post(AppNotificationItem(
            icon: "megaphone.fill", iconColorHex: "#A78BFA",
            title: title.isEmpty ? body : title,
            body:  title.isEmpty ? "" : body,
            time:  loc("notif.time.now"),
            isUrgent: true
        ), pushToDevice: false)
    }
}

// MARK: - App Entry

@main
struct DiPoApp: App {

    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    @AppStorage("appearance_mode") private var appearanceMode: String = "system"

    private static let sharedModelContainer: ModelContainer = {
        let schema = Schema([
            BankCard.self, TxRecord.self, SalarySchedule.self,
            DebtRecord.self, SavingsGoal.self,
            // Per-card Smart Budget allocations (50/30/20 daily/lifestyle/invest).
            // One row per card the user has configured; cards without a row fall
            // back to global defaults from SmartBudgetManager.
            CardBudgetConfig.self
        ])
        let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: false)
        do {
            return try ModelContainer(for: schema, configurations: config)
        } catch {
            print("[DiPo] Store error, wiping: \(error)")
            try? FileManager.default.removeItem(at: config.url)
            guard let fresh = try? ModelContainer(for: schema, configurations: config) else {
                print("[DiPo] FATAL: Could not recreate SwiftData store after wipe. Schema: \(schema)")
                fatalError("SwiftData store unrecoverable — check schema consistency.")
            }
            return fresh
        }
    }()

    init() {
        FirebaseApp.configure()

        if let path = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist"),
           let plist = NSDictionary(contentsOfFile: path),
           let clientID = plist["CLIENT_ID"] as? String {
            GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: clientID)
        } else if let clientID = Bundle.main.object(forInfoDictionaryKey: "GIDClientID") as? String {
            GIDSignIn.sharedInstance.configuration = GIDConfiguration(clientID: clientID)
        }
    }

    private var resolvedColorScheme: ColorScheme? {
        switch appearanceMode {
        case "dark":  return .dark
        case "light": return .light
        default:      return nil
        }
    }

    var body: some Scene {
        WindowGroup {
            RootView()
                // ✅ Force full re-render when language switches so all Text() updates instantly
                .id(LanguageManager.shared.renderID)
                .preferredColorScheme(resolvedColorScheme)
                .onOpenURL { url in
                    // Two URL schemes share this hook:
                    //   1. `dipo://...` — Home Screen widget deep-links.
                    //   2. Google's reverse-client-ID scheme — Google Sign-In OAuth.
                    // We branch on scheme so Google's library only sees what's
                    // intended for it; otherwise it spews "unable to parse callback URL".
                    if url.scheme == "dipo" {
                        switch url.host {
                        case "add-transaction":
                            // Reuse the same NotificationCenter signal that the
                            // empty-state CTAs in HomeView / StatisticsView post.
                            // MainTabView owns the sheet binding and handles the
                            // no-cards-yet edge case there.
                            NotificationCenter.default.post(name: .requestOpenAddTransaction, object: nil)
                        case "upgrade-royal":
                            // Free-user Smart Insights teaser in the widget
                            // routes here. Open the Royal paywall directly
                            // so the conversion path is as short as possible —
                            // tap widget → see paywall, no detours through
                            // settings tab first.
                            NotificationCenter.default.post(name: .requestOpenPaywall, object: nil)
                        case "support":
                            // Support-reply notifications ("Learn more") deep-link
                            // here. Open the Support screen so the user lands on
                            // their ticket thread.
                            NotificationCenter.default.post(name: .requestOpenSupport, object: nil)
                        default:
                            break  // Unknown dipo:// host — ignore silently.
                        }
                    } else {
                        GIDSignIn.sharedInstance.handle(url)
                    }
                }
                .modelContainer(Self.sharedModelContainer)
        }
    }
}

// MARK: - Smooth Appearance Transition

func performAppearanceTransition(to newMode: String, duration: Double = 0.45) {
    guard let window = UIApplication.shared.connectedScenes
        .compactMap({ $0 as? UIWindowScene })
        .flatMap({ $0.windows })
        .first(where: { $0.isKeyWindow }) else { return }

    let renderer = UIGraphicsImageRenderer(bounds: window.bounds)
    let snapshot = renderer.image { window.layer.render(in: $0.cgContext) }

    let imageView = UIImageView(image: snapshot)
    imageView.frame = window.bounds
    imageView.alpha = 1
    window.addSubview(imageView)

    UserDefaults.standard.set(newMode, forKey: "appearance_mode")

    DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
        UIView.animate(withDuration: duration, delay: 0,
                       options: [.curveEaseInOut],
                       animations: { imageView.alpha = 0 },
                       completion: { _ in imageView.removeFromSuperview() })
    }
}
